title: Земли Былых Легенд
email: dmitry.radionov69@gmail.com
encoding: utf-8
description: >-
  Wiki база по сеттингу Земли Былых Легенд
baseurl: ""
domain: zemlibylykhlegend.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://zemlibylykhlegend.github.io  # the base hostname and protocol for your site, e.g. http://example.com
github_username:  ZemliBylykhLegend

color_scheme: reading

sass:
  quiet_deps: true
  silence_deprecations:
    - import

lsi: false
safe: false
logo: "/assets/images/zbl.png"
plugins:
  - jekyll-feed
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Поддержка Markdown в `_pages`
collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"  # Использует `_layouts/page.html`

creature_cards:
  default_position: "right"
  image_path: "/assets/images/creatures/"
  enable_collapsible: true

auto_cross_ref:
  enabled: true
  base_dir: 'docs'
  subdirs:
    - glosariy
    - bestiariy
  excluded_words:
    - народ
    - народа
    - народы
    - народом
    - народе
    - народов
    - народами
    - народам
    - стоянка
    - условия
    - наркотиков
    - наказывает
    - ясного
    - усопшими
    - наклоном
    - нарубленой
    - нарубленным
    - усложняет
    - усилиями
    - наростов
    - усы
    - устойчиво
    - уснувшего
    - наркотических
    - на
    - та
    - атака
    - атаку
    - атаки
    - атакой
    - над
    - там
    - сих
    - края
    - атак